version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ~/www:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php56
      - php74
      - php81
      - php82

  php56:
    image: php:5.6-fpm
    ports:
      - "9056:9000"
    volumes:
      - ~/www:/var/www

  php74:
    image: php:7.4-fpm
    ports:
      - "9074:9000"
    volumes:
      - ~/www:/var/www

  php81:
    image: php:8.1-fpm
    ports:
      - "9081:9000"
    volumes:
      - ~/www:/var/www

  php82:
    image: php:8.2-fpm
    ports:
      - "9084:9000"
    volumes:
      - ~/www:/var/www

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - "6969:80"
    environment:
      PMA_HOST: host.docker.internal  # Replace with your MySQL host (e.g., localhost or an IP)
      PMA_USER: root   # Replace with your MySQL user
      PMA_PASSWORD: password  # Replace with your MySQL password
    # No need for 'depends_on' for db since it's not included
