version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ~/www:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php56
      - php74
      - php81
      - php82

  php56:
    build:
      context: .
      dockerfile: Dockerfile-5.6
    ports:
      - "9056:9000"
    volumes:
      - ~/www:/var/www

  php74:
    build:
      context: .
      dockerfile: Dockerfile-7.4
    ports:
      - "9074:9000"
    volumes:
      - ~/www:/var/www

  php81:
    build:
      context: .
      dockerfile: Dockerfile-8.1
    ports:
      - "9081:9000"
    volumes:
      - ~/www:/var/www

  php82:
    build:
      context: .
      dockerfile: Dockerfile-8.2
    ports:
      - "9084:9000"
    volumes:
      - ~/www:/var/www

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - "6969:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: root
      PMA_PASSWORD: password
