FROM php:5.6-fpm-alpine

# Install system dependencies
RUN apk add --no-cache \
    curl-dev \
    libzip-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libxml2-dev

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install \
    curl \
    mysqli \
    pdo \
    pdo_mysql \
    mbstring \
    json \
    gd \
    zip \
    opcache

# Create appuser for better security
RUN addgroup -g 1000 appuser && \
    adduser -D -s /bin/sh -u 1000 -G appuser appuser

# Switch to appuser
USER appuser

# Set working directory
WORKDIR /var/www/html
